### ISSUE TITLE
Simplifying InvertibleScrollView

### ISSUE THREAD

**Issue by ktoh** [650Industries/react-native-invertible-scroll-view#14]
I like this library, but feel like it could be more useful if it encapsulated more of the component setup.

I think the majority of those looking to use invertible scroll views are simply looking for a way to get a `<ScrollView>` or `<ListView>` component with reverse scrolling (e.g. for a chat application, terminal log, or any number of common use cases).
### Ideally...

The best way to do this in react-native would be to simply expose a prop on those respective components so that scrolling can just be declared, e.g.

```
<ListView   scrollDirection="reverse" ... />
<ScrollView scrollDirection="reverse" ... />
```

I would really like to see this in react-native as it solves a really common UX need in the most composable and declarative way without involving any (redundant) new components.
### Until then...

This library is an excellent stopgap.  But it provides an incomplete solution because doesn't provide a simple component that just gets the job done:  it requires developers to manually compose the inverted view using `renderScrollComponent`, reversing the datasource, etc.
### Can we...

...simply provide a couple components which behave exactly like `<ListView>` and `<ScrollView>`, except with inverted scrolling?  For example:
- `<ReverseScrollView>`, which extends ScrollView
- `<ReverseListView>`, which extends ListView

...these components would behave exactly like ScrollView and ListView, with the same props, dataSource, etc.  Only the scroll direction would be reversed.  No more need to worry about how `renderScrollComponent` works, or how to deal with reversed data sources.

I think this would provide much better composability, learnability, and usability for developers.  It would also provide a simple migration path in the future if react-native decides to offer something like a `scrollDirection` prop, since developers would already have written to a consistent set of props, events, etc.

**Comment by ide** [comment]
The things I care about the most are composition, having a high ceiling (making complex apps possible with minimal extra complexity), and supporting a healthy ecosystem. We actually increase composability by keeping these features out of ScrollView as individually cohesive libs instead of adding them in as props. For example, the Android ViewPager component was recently open-sourced upstream. I haven't tried it yet, but conceivably you could use InvertibleScrollView to flip a ViewPager. We can compose these different pieces in ways that have not been anticipated.

As for complex apps, my goal is for programmers to understand how this library works and use it in ways that work for their apps. In InvertibleScrollView's case, there are some gotchas that can't be covered up. For example marginTop on the ScrollView's content container will be rendered at the bottom because of the inversion, and that can't be handled robustly because the StyleSheet registry is a private implementation detail of RN. So it's better for programmers to understand how InvertibleScrollView works and use it as a tool rather than a crutch.

Ecosystem - React Native is only a couple years old and hasn't seen really heavy use until recently so I would like to encourage experimentation and composition by introducing a composable InvertibleScrollView, RefreshableScrollView, InfiniteScrollView instead of baking these props into the kitchen sink like `<ScrollView inverted onRefresh onLoadMore>`. After a 12-18 months we may have a better idea of what features are really good to include into a component like ScrollView or ListView but I think it's way too early for that now, and the team at FB also has to be willing to maintain the API.

So if you want to publish ReverseScrollView and ReverseListView using InvertibleScrollView I'm in support of that but the purpose of this repo is to let such components be built using these building blocks. I agree the components you proposed could be easier to get started with and want to be clear that I don't think they are bad ideas and I would love InvertibleScrollView to enable them -- just I believe they should be separate from InvertibleScrollView.

**Comment by ktoh** [comment]
@ide your thought process makes sense.  
You're right that InvertibleScrollView is actually a more composable solution, even if it is not quite at the level of encapsulation that users might expect.  And this level of abstraction is more appropriate for this stage of react-native's lifecycle given that the community is still threshing out what is common vs kitchen-sink.

Upon reflection, maybe the only real critique here is that `InvertibleScrollView` is maybe a little oddly named since it invites  comparison with `ScrollView` and `ListView` ...when in fact it serves a different function as a view composer....so something like `ScrollInverter` might have been more appropriate in hindsight.

I agree with your suggestion that components like `ReverseScrollView` and `ReverseListView` would be better published separately.....when I find time I'll see if there's a reasonable way to build this given some of the constraints you noted (like margins, etc).  

Thanks!

**Comment by ide** [comment]
The name InvertibleScrollView was inspired by ListView, which is actually simply a wrapper around a ScrollView and also supports renderScrollComponent. You could say it's a ScrollLister :) If you publish ReverseScroll/ListView and want me to tweet about it just give me a shout.
