### ISSUE TITLE
If items aren't enough list view items are shown at the bottom ?

### ISSUE THREAD

**Issue by jawadrehman** [650Industries/react-native-invertible-scroll-view#5]
If I have sufficient items it displays fine, but if its just 2 or 3 items then the items are shown far at the bottom . 

here's my styles

  container: {
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    backgroundColor: 'white',
    flex : 1,
    padding : 20,
  },

  list :{
    borderColor: 'gray',
    borderWidth : 1,
    margin : 20,
    marginTop : 100
  },
  load_more : {
    height : 100,
  },

---

and the render

<View style={styles.container}>
        <ListMessageHistory style={styles.list} ref="ListMessageHistory" ></ListMessageHistory>
        <Button style={styles.load_more} onPress={this._retrieve_archive_messages_callback}>Load Previous</Button>
      </View>

**Comment by ide** [comment]
The inverted scroll view flips everything so that content fills from the bottom to the top so this is the intended behavior. You may need to adjust the content insets of your scroll view too. Turn off automatic inset adjustment if you are using NavigatorIOS.

If you want to fill your ListView or ScrollView from the top to bottom, then you should reverse the items in the data source or list of child components, respectively.

**Comment by joshuapinter** [comment]
There are a couple of great solutions to this issue over at https://github.com/exponentjs/react-native-invertible-scroll-view/issues/11#issuecomment-216000196
