### ISSUE TITLE
Animation when unshift new elment

### ISSUE THREAD

**Issue by maicaiyao** [650Industries/react-native-invertible-scroll-view#9]
Hi I'm using this library for my messaging app. Is there or will there be support of the animation effect when I unshift an element to the list? 

Currently the frame just re-renders and the list elements magically jumps to the new position. I tried to use layout animation but the result is not as expected.

Thanks!

**Comment by ide** [comment]
Hi @maicaiyao, we probably won't support animation in this component because animating the list items is not a feature of InvertibleScrollView.

However, if you wanted to animate a list item, you could try wrapping the item in an Animated.View with `height: 0, overflow: 'hidden'` and animate the wrapper's height to the full height of the list item (use the `onLayout` event to get it).
